application: gcpug-shonan-vol3-ryu22e
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: _build/html/index.html
  upload: _build/html/index.html
  secure: always
  # Google Appsドメイン認証を使わないなら「login: admin」にする。
  login: required

- url: /(.*)
  static_files: _build/html/\1
  upload: _build/html/.*
  secure: always
  # Google Appsドメイン認証を使わないなら「login: admin」にする。
  login: required

- url: /.*
  script: _go_app
