# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
            ],
            options={
                'verbose_name': '著者',
                'verbose_name_plural': '著者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('published_at', models.DateField(db_index=True, verbose_name='出版日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='著者')),
            ],
            options={
                'verbose_name': '書籍',
                'ordering': ('-published_at',),
                'verbose_name_plural': '書籍',
            },
        ),
    ]
